name: Sync Fork
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/locustio/locust.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
